services:
  db:
    build: db/
    ports:
      - "5432:5432"

  site_viewer:
    build:
      context: site_viewer/
      dockerfile: Dockerfile.dev
    volumes:
      - ./site_viewer:/usr/src/site_viewer:ro
      - ./cert:/usr/src/cert
    depends_on:
      - db
    ports:
      - "8443:8443"

volumes:
  cert:
