FROM python:3

WORKDIR /usr/src/site_viewer

RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
ENV PATH="/root/.local/bin:${PATH}"

CMD ["./start_dev.sh"]
